pub mod database;
pub mod tab_manager;
pub mod tab_isolation;
pub mod fingerprint;
pub mod proxy;
pub mod http_client;
pub mod scraper_util;
pub mod security;
pub mod webview_manager;
pub mod browser_tab_manager;
pub mod free_ip_providers;
pub mod storage;
pub mod backup;
pub mod browser_controls;
pub mod local_proxy;
pub mod pac_server;
pub mod proxy_rotation;
pub mod proxy_validator;
pub mod chromium_engine;
pub mod ad_verification;

pub use database::{Database, DatabaseError};
pub use tab_manager::TabIPManager;
pub use tab_isolation::{TabProfile, NetworkConfig, TabStatus};
pub use fingerprint::BrowserFingerprint;
pub use proxy::{ProxyManager, ProxySettings, ProxyType, FreeProxy, ProxyTestResult};
pub use http_client::{HttpClient, PublicIpDetector, PublicIpInfo};
pub use scraper_util::ProxyScraper;
pub use security::{SecurityManager, BookmarkInput, ProxyInput};
pub use webview_manager::{WebviewManager, WebviewTab};
pub use browser_tab_manager::{BrowserTabManager, BrowserTab, CreateTabConfig, TabStats};
pub use free_ip_providers::{FreeIpProvider, FreeIpProviderManager};
pub use storage::{StorageEngine, Cookie, HistoryEntry, Bookmark};
pub use backup::{BackupManager, BackupData, BackupOptions, BackupInfo, AutoBackupSettings};
pub use browser_controls::{BrowserController, BrowserState, BrowserSettings, WebRtcPolicy};
pub use local_proxy::{LocalProxyServer, LocalProxyManager, ProxyConnection};
pub use pac_server::{PacServer, PacManager};
pub use proxy_rotation::{ProxyRotationManager, ProxyRotationStrategy, ProxyMetrics, ProxySessionStats};
pub use proxy_validator::{ProxyValidator, ProxyValidatorConfig, ValidationResult, ProxyHealthChecker};
pub use chromium_engine::{ChromiumEngine, ChromiumEngineConfig, BrowserEngineManager, BrowserEngineType, ChromiumTab, EngineCapabilities};
pub use ad_verification::{AdVerificationManager, AdVerificationConfig, ImpressionVerification, ImpressionData, VastVerification, VpaidVerification, VerificationSession, SessionStats, ViewabilityStatus, FraudSignal, AdFormat, VerificationStandard};
